shell fish

font_size 12.2

#transparent background (works with picom [.config/picom.conf])
dynamic_background_opacity yes
background_opacity 0.9
background_blur 1

# unable window close confirmation
confirm_os_window_close 0

window_padding_width 9 10 9 10

# ========== CURSOR ===========
# cursor movement animation (unabled)
cursor_trail 0
cursor_shape beam
cursor_beam_thickness 1.0
cursor_beam_height 1

scrollbar never

# number of lines of history to keep in memory
scrollback_lines 2000

include colors.conf

