general {
    lock_cmd = pidof hyprlock || hyprlock       # Kilit komutu çağrıldığında hyprlock çalıştır
    before_sleep_cmd = hyprlock                 # Bilgisayar uyumadan ÖNCE ekranı kilitle (Güvenlik için)
    after_sleep_cmd = hyprctl dispatch dpms on  # Uykudan uyanınca ekrana sinyal gönder
}

# Lock screen after 5 minutes (300 seconds)
listener {
    timeout = 53
    on-timeout = loginctl lock-session
}

# Turn off screen light after 5,5 minutes (330 seconds) (dpms)
listener {
    timeout = 10 
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend computer after 10 minutes (600 seconds)
listener {
    timeout = 1015
    on-timeout = systemctl suspend
}
